"""
Backend-Neutral Engineering Agent Adapter Contract for Generic DAIO (Phase S5.1).
Defines request, proposal, and verification interfaces without depending on specific LLM vendors.
"""

from __future__ import annotations
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
import datetime
from typing import Any, Dict, List, Optional


@dataclass
class ProposedFileEdit:
    """A proposed modification to a file within the workspace."""
    file_path: str
    new_content: str
    description: str = ""
    is_deletion: bool = False


@dataclass
class AgentTaskRequest:
    """Backend-neutral input contract for an autonomous engineering task."""
    work_id: str
    change_id: str
    requested_action: str
    project_root: str
    allowed_scope: List[str] = field(default_factory=list)
    frozen_paths: List[str] = field(default_factory=list)
    context_files: Dict[str, str] = field(default_factory=dict)
    backend_config: Dict[str, Any] = field(default_factory=dict)
    timeout_seconds: int = 300


@dataclass
class AgentTaskProposal:
    """
    Backend-neutral proposal returned by a Coding Agent.
    The agent does NOT write directly to disk; it proposes edits for DAIO policy validation.
    """
    work_id: str
    success: bool
    proposed_edits: List[ProposedFileEdit] = field(default_factory=list)
    backend_identity: str = "GENERIC_AGENT"
    model_name: str = "UNKNOWN"
    reasoning_summary: str = ""
    error_message: Optional[str] = None
    started_at: str = field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc).isoformat())
    completed_at: str = field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc).isoformat())
    raw_response: str = ""


class EngineeringAgentAdapter(ABC):
    """
    Abstract contract for an unattended coding agent backend.
    Implementations (Gemini, Claude, OpenAI, Aider, CLI) must adhere to this interface.
    """

    @abstractmethod
    async def propose_task_solution(self, request: AgentTaskRequest) -> AgentTaskProposal:
        """
        Generate proposed code edits based on the natural-language requested_action and workspace context.
        Must NOT write directly to disk or perform git operations.
        """
        raise NotImplementedError


class MockEngineeringAgentAdapter(EngineeringAgentAdapter):
    """Mock agent adapter for deterministic contract testing."""

    def __init__(self, canned_proposals: Optional[List[AgentTaskProposal]] = None) -> None:
        self.canned_proposals = canned_proposals or []
        self.invocations: List[AgentTaskRequest] = []

    async def propose_task_solution(self, request: AgentTaskRequest) -> AgentTaskProposal:
        self.invocations.append(request)
        if self.canned_proposals:
            return self.canned_proposals.pop(0)
        return AgentTaskProposal(
            work_id=request.work_id,
            success=True,
            backend_identity="MOCK_AGENT",
            model_name="mock-model-v1",
            proposed_edits=[
                ProposedFileEdit(file_path="src/service.py", new_content="# auto-generated by mock\n")
            ]
        )
