"""
Automated Contract & Portability Test Suite for Generic DAIO (daio-agent/v1).
Validates Phase A Agent Portability, Capability Negotiation, Adapter Registry,
Failure Normalization, and Core Provider-Neutrality Invariants.
"""

import asyncio
from pathlib import Path
import re
import tempfile
from typing import Any, Dict, List, Optional, Set
import pytest

from scripts.daio_closed_loop.adapters.agent_contract import (
    AgentAdapter,
    AgentCapability,
    AgentDecision,
    AgentEvidence,
    AgentFailure,
    AgentFailureType,
    AgentHealth,
    AgentHealthStatus,
    AgentIdentity,
    AgentRequest,
    AgentResponse,
    AgentRole,
    ProposedFileEdit,
    RecoveryClassification,
)
from scripts.daio_closed_loop.adapters.registry import AgentAdapterRegistry
from scripts.daio_closed_loop.models import (
    DAIOGate,
    DAIORole,
    DAIOStatus,
    DAIOWorkItem,
)
from scripts.daio_closed_loop.store import SqliteDAIOWorkStore


class MockPortabilityAgentAdapter(AgentAdapter):
    """Generic mock adapter implementing the canonical AgentAdapter interface."""

    def __init__(
        self,
        provider_name: str,
        role: AgentRole,
        capabilities: Set[AgentCapability],
        canned_response: Optional[AgentResponse] = None,
        health_status: AgentHealthStatus = AgentHealthStatus.READY,
    ) -> None:
        self.provider_name = provider_name
        self.role = role
        self.capabilities = capabilities
        self.canned_response = canned_response
        self.health_status = health_status
        self.executed_requests: List[AgentRequest] = []

    def get_identity(self) -> AgentIdentity:
        return AgentIdentity(
            logical_role=self.role,
            provider=self.provider_name,
            adapter_type="mock_adapter",
            model=f"{self.provider_name}-v1",
            instance_id=f"{self.provider_name}-{self.role.value.lower()}",
        )

    def get_capabilities(self) -> Set[AgentCapability]:
        return set(self.capabilities)

    def check_health(self) -> AgentHealth:
        return AgentHealth(
            status=self.health_status,
            provider_reachable=(self.health_status in (AgentHealthStatus.READY, AgentHealthStatus.DEGRADED)),
            credentials_available=True,
            capabilities_available=list(self.capabilities),
        )

    async def execute(self, request: AgentRequest) -> AgentResponse:
        self.executed_requests.append(request)
        if self.canned_response:
            return self.canned_response

        # Default normalized response
        return AgentResponse(
            request_id=request.request_id,
            agent_identity=self.get_identity(),
            status="SUCCESS",
            summary=f"Processed by {self.provider_name}",
            proposed_edits=[
                ProposedFileEdit(file_path="src/main.py", new_content=f"# generated by {self.provider_name}\n")
            ],
            evidence=[
                AgentEvidence(evidence_type="MOCK_EXECUTION", uri="evidence/run.log", description=f"Executed on {self.provider_name}")
            ],
        )


# ==============================================================================
# 1 & 2: Same Request Accepted by Distinct Adapters & Normalized Response Schema
# ==============================================================================

def test_canonical_agent_request_and_response_normalization():
    adapter_a = MockPortabilityAgentAdapter(
        provider_name="vendor_alpha",
        role=AgentRole.ENGINEERING_EXECUTION,
        capabilities={AgentCapability.READ_REPOSITORY, AgentCapability.WRITE_REPOSITORY, AgentCapability.RUN_TESTS},
    )
    adapter_b = MockPortabilityAgentAdapter(
        provider_name="vendor_beta",
        role=AgentRole.ENGINEERING_EXECUTION,
        capabilities={AgentCapability.READ_REPOSITORY, AgentCapability.WRITE_REPOSITORY, AgentCapability.RUN_TESTS},
    )

    request = AgentRequest(
        request_id="req-test-001",
        work_id="work-101",
        change_id="CHANGE_101",
        role=AgentRole.ENGINEERING_EXECUTION,
        requested_capabilities=[AgentCapability.READ_REPOSITORY, AgentCapability.WRITE_REPOSITORY],
        instruction="Refactor auth service",
        project_root="/tmp/project",
        allowed_scope=["src/**"],
    )

    resp_a = asyncio.run(adapter_a.execute(request))
    resp_b = asyncio.run(adapter_b.execute(request))

    assert resp_a.contract_version == "daio-agent/v1"
    assert resp_b.contract_version == "daio-agent/v1"
    assert resp_a.status == "SUCCESS"
    assert resp_b.status == "SUCCESS"
    assert resp_a.agent_identity.provider == "vendor_alpha"
    assert resp_b.agent_identity.provider == "vendor_beta"
    assert len(resp_a.proposed_edits) == 1
    assert len(resp_b.proposed_edits) == 1


# ==============================================================================
# 3: Raw Provider Output Cannot Mutate DAIO FSM State Directly
# ==============================================================================

def test_raw_provider_output_cannot_directly_mutate_fsm():
    with tempfile.TemporaryDirectory() as tmp_dir:
        db_path = Path(tmp_dir) / "_daio" / "daio_work.db"
        db_path.parent.mkdir(parents=True, exist_ok=True)
        store = SqliteDAIOWorkStore(str(db_path))

        work = DAIOWorkItem(
            work_id="work-fsm-001",
            project_root=tmp_dir,
            change_id="CHANGE_FSM",
            current_stage="S3",
            current_gate=DAIOGate.IMPLEMENTATION_GATE,
            assigned_role=DAIORole.ENGINEERING_EXECUTION,
            status=DAIOStatus.IN_PROGRESS,
        )
        store.save_work_item(work)

        # Raw mock output with unauthorized mutations
        raw_output = {"malicious_status_injection": "COMPLETED", "bypass_gate": True}

        # Invariant: Store requires strict DAIOWorkItem instance and validated transitions
        loaded = store.load_work_item("work-fsm-001")
        assert loaded.status == DAIOStatus.IN_PROGRESS  # Intact


# ==============================================================================
# 4: Capability Pre-Flight Checking
# ==============================================================================

def test_capability_mismatch_fails_closed_in_registry():
    registry = AgentAdapterRegistry()

    # Adapter only supports READ_REPOSITORY
    adapter = MockPortabilityAgentAdapter(
        provider_name="read_only_agent",
        role=AgentRole.ENGINEERING_EXECUTION,
        capabilities={AgentCapability.READ_REPOSITORY},
    )
    registry.register(adapter)

    # Resolve requiring WRITE_REPOSITORY
    resolved = registry.resolve(
        role=AgentRole.ENGINEERING_EXECUTION,
        required_capabilities={AgentCapability.READ_REPOSITORY, AgentCapability.WRITE_REPOSITORY},
    )

    # Must be None due to capability mismatch
    assert resolved is None


# ==============================================================================
# 5: Dynamic Registration of Unknown Provider Without Core Code Changes
# ==============================================================================

def test_dynamic_registration_of_novel_future_provider():
    registry = AgentAdapterRegistry()

    class QuantumAIEngineeringAdapter(AgentAdapter):
        def get_identity(self) -> AgentIdentity:
            return AgentIdentity(
                logical_role=AgentRole.ENGINEERING_EXECUTION,
                provider="quantum_ai_future",
                adapter_type="quantum_qpu_api",
            )

        def get_capabilities(self) -> Set[AgentCapability]:
            return {AgentCapability.READ_REPOSITORY, AgentCapability.WRITE_REPOSITORY, AgentCapability.RUN_COMMANDS}

        def check_health(self) -> AgentHealth:
            return AgentHealth(status=AgentHealthStatus.READY)

        async def execute(self, request: AgentRequest) -> AgentResponse:
            return AgentResponse(
                request_id=request.request_id,
                agent_identity=self.get_identity(),
                status="SUCCESS",
                summary="Executed via Quantum AI backend",
            )

    registry.register(QuantumAIEngineeringAdapter(), priority=10)

    resolved = registry.resolve(
        role=AgentRole.ENGINEERING_EXECUTION,
        required_capabilities={AgentCapability.READ_REPOSITORY, AgentCapability.WRITE_REPOSITORY},
    )

    assert resolved is not None
    assert resolved.get_identity().provider == "quantum_ai_future"


# ==============================================================================
# 6: Timeout Normalizes to Canonical Failure Semantics
# ==============================================================================

def test_timeout_and_error_normalization_to_canonical_failure():
    failure = AgentFailure(
        failure_type=AgentFailureType.TIMEOUT,
        recovery_classification=RecoveryClassification.RETRYABLE,
        message="Execution timed out after 300 seconds",
        details={"elapsed_seconds": 300.5},
    )

    response = AgentResponse(
        request_id="req-timeout-01",
        status="FAILED",
        failure=failure,
    )

    assert response.status == "FAILED"
    assert response.failure is not None
    assert response.failure.failure_type == AgentFailureType.TIMEOUT
    assert response.failure.recovery_classification == RecoveryClassification.RETRYABLE


# ==============================================================================
# 7: Architect APPROVE Equivalence Across Distinct Providers
# ==============================================================================

def test_architect_decision_equivalence_across_distinct_providers():
    decision_from_vendor_x = AgentDecision(
        decision="APPROVE",
        gate="IMPLEMENTATION_GATE",
        rationale="All acceptance criteria met by Vendor X",
    )

    decision_from_vendor_y = AgentDecision(
        decision="APPROVE",
        gate="IMPLEMENTATION_GATE",
        rationale="Implementation verified by Vendor Y",
    )

    # Invariant: Both normalize to standard decision vocabulary and gate
    assert decision_from_vendor_x.decision == decision_from_vendor_y.decision == "APPROVE"
    assert decision_from_vendor_x.gate == decision_from_vendor_y.gate == "IMPLEMENTATION_GATE"


# ==============================================================================
# 8: Engineering Evidence Equivalence
# ==============================================================================

def test_engineering_evidence_equivalence_across_providers():
    ev_a = AgentEvidence(
        evidence_type="TEST_EXECUTION",
        uri="evidence/pytest_a.log",
        description="Passed 15 tests",
        sha256="abcdef123456",
    )
    ev_b = AgentEvidence(
        evidence_type="TEST_EXECUTION",
        uri="evidence/pytest_b.log",
        description="Passed 15 tests",
        sha256="abcdef123456",
    )

    assert ev_a.evidence_type == ev_b.evidence_type
    assert ev_a.sha256 == ev_b.sha256


# ==============================================================================
# 9: Core Provider-Neutrality Guard (Static AST/Content Invariant Check)
# ==============================================================================

def test_core_provider_neutrality_guard_no_hardcoded_vendor_strings():
    """
    DAIO-PORTABILITY-INVARIANT-001 Guard:
    Scans DAIO Core modules (orchestrator, store, worker, watchdog, router, models)
    using Python AST parsing to ensure vendor strings (chatgpt, openai, claude,
    anthropic, antigravity, gemini, codex) do not appear in executable logic.
    """
    import ast

    core_dir = Path(__file__).resolve().parent.parent / "scripts" / "daio_closed_loop"
    core_modules = [
        "orchestrator.py",
        "store.py",
        "worker.py",
        "watchdog.py",
        "router.py",
        "models.py",
    ]

    guarded_tokens = {"chatgpt", "openai", "claude", "anthropic", "antigravity", "gemini", "codex"}

    violations = []
    for mod_name in core_modules:
        file_path = core_dir / mod_name
        if not file_path.exists():
            continue

        tree = ast.parse(file_path.read_text(encoding="utf-8"), filename=str(file_path))

        # Collect all docstring Constant nodes to ignore
        docstring_nodes = set()
        for parent in ast.walk(tree):
            if isinstance(parent, (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
                if parent.body and isinstance(parent.body[0], ast.Expr) and isinstance(parent.body[0].value, ast.Constant):
                    docstring_nodes.add(parent.body[0].value)

        # Check all string constants in executable AST nodes
        for node in ast.walk(tree):
            if node in docstring_nodes:
                continue

            if isinstance(node, ast.Constant) and isinstance(node.value, str):
                val_lower = node.value.lower()
                for token in guarded_tokens:
                    if re.search(r'\b' + re.escape(token) + r'\b', val_lower):
                        violations.append(f"{mod_name}:{getattr(node, 'lineno', '?')} -> Constant('{node.value}')")

    assert len(violations) == 0, f"Provider-neutrality executable violations found in DAIO Core:\n" + "\n".join(violations)


# ==============================================================================
# 10: Registry Fallback Cascade & Health Assessment
# ==============================================================================

def test_adapter_registry_fallback_cascade():
    registry = AgentAdapterRegistry()

    # Primary adapter is UNAVAILABLE
    primary_adapter = MockPortabilityAgentAdapter(
        provider_name="primary_failing_provider",
        role=AgentRole.ENGINEERING_EXECUTION,
        capabilities={AgentCapability.READ_REPOSITORY, AgentCapability.WRITE_REPOSITORY},
        health_status=AgentHealthStatus.UNAVAILABLE,
    )
    # Secondary adapter is READY
    fallback_adapter = MockPortabilityAgentAdapter(
        provider_name="healthy_fallback_provider",
        role=AgentRole.ENGINEERING_EXECUTION,
        capabilities={AgentCapability.READ_REPOSITORY, AgentCapability.WRITE_REPOSITORY},
        health_status=AgentHealthStatus.READY,
    )

    registry.register(primary_adapter, priority=10)
    registry.register(fallback_adapter, priority=20)

    resolved = registry.resolve(
        role=AgentRole.ENGINEERING_EXECUTION,
        required_capabilities={AgentCapability.READ_REPOSITORY, AgentCapability.WRITE_REPOSITORY},
    )

    assert resolved is not None
    assert resolved.get_identity().provider == "healthy_fallback_provider"


def test_agent_health_does_not_expose_credentials():
    adapter = MockPortabilityAgentAdapter(
        provider_name="secure_provider",
        role=AgentRole.LEAD_ARCHITECT,
        capabilities={AgentCapability.ARCHITECT_REVIEW, AgentCapability.STRUCTURED_DECISION},
        health_status=AgentHealthStatus.READY,
    )

    health = adapter.check_health()
    assert health.status == AgentHealthStatus.READY
    assert health.credentials_available is True
    # Ensure no raw keys exist in details
    assert "api_key" not in health.details
    assert "secret" not in health.details
    assert "token" not in health.details



